name: remotecontrol_lib
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  uuid: ^3.0.6
  win32: ^5.7.0
  intl: ^0.19.0
  flutter:
    sdk: flutter
  fluent_ui: ^4.9.1
  grpc:
  protobuf:
  xml: ^6.5.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
